### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by Ayush7614** [Fork-N-Forge/Python-Sala#1]
Build a Python script that fetches real-time weather data for a user-specified location using an API like OpenWeatherMap.

**Comment by aniketakumari** [comment]
I am excited to submit a pull request for the  issue titled "Build a Python script that fetches real-time weather data for a user-specified location using an API like OpenWeatherMap."

I plan to develop a Python script that leverages the OpenWeatherMap API to fetch real-time weather data for a location specified by the user. This script offers a convenient way for users to access up-to-date weather information effortlessly. 

Could you assign me this issue so that I start working on the issue right away?

Thank you so much!

**Comment by sahalhes** [comment]
@Ayush7614 Hey I already did PR. Please check and tell if there any changes required.
